## server port config - 사용하려는 포트를 지정
server:
  port: 8001

## driver config - 사용하려는 DB의 정보를 입력
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    username: ohgiraffers
    password: ohgiraffers

## mybatis config - 패키지 구성이 똑같지 않아도 인터페이스와 xml 파일을 연결한다.
mybatis:
  mapper-locations : mappers/**/*.xml