# port
  server:
    port: 8001


# DB
  spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/menudb
      username: "ohgiraffers"
      password: "ohgiraffers"


# mappers
  mybatis:
    mapper-locations:
       mappers/**/*.xml